# Generated by Django 5.0.6 on 2024-07-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20240707_0029"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="registration_time",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="usage",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
