# Generated by Django 5.0.6 on 2024-07-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_registration_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_ip", models.CharField(max_length=100)),
            ],
        ),
    ]
