# Generated by Django 5.0.6 on 2024-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_dbserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbserver",
            name="server_name",
            field=models.CharField(default="host_server", max_length=100),
        ),
    ]
