# Generated by Django 5.0.6 on 2024-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_dbserver_server_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.CharField(max_length=100)),
                ("server_ip", models.CharField(max_length=100)),
                ("port", models.IntegerField()),
                ("uuid", models.CharField(max_length=100)),
                ("alter_id", models.IntegerField()),
                ("network", models.CharField(max_length=100)),
                ("network_type", models.CharField(max_length=100)),
                ("protocal", models.CharField(max_length=100)),
            ],
        ),
    ]
