# Generated by Django 5.0.6 on 2024-07-07 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_protocalconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DbServer",
        ),
        migrations.DeleteModel(
            name="ProtocalConfig",
        ),
    ]
