# Generated by Django 5.0.6 on 2024-07-07 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_protocol_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="connection_url",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="usage",
        ),
    ]
