# Generated by Django 5.0.6 on 2024-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_customuser_connection_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="reset_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
