# Generated by Django 5.0.6 on 2024-07-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cluster",
            "0008_alter_dbserver_options_alter_protocalconfig_options_and_more",
        ),
        ("users", "0010_customuser_reset_token_customuser_reset_token_expiry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="protocol_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="cluster.protocalconfig",
                verbose_name="Protocal Config",
            ),
        ),
    ]
