# Generated by Django 5.0.6 on 2024-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="customer_group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Customer Group"
            ),
        ),
    ]
