# Generated by Django 5.0.7 on 2024-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_stripe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="amount_total",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="payer_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="payer_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="payment_intent",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
