# Generated by Django 5.0.7 on 2024-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_stripe", "0002_alter_stripepaymentlink_amount_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripepaymentlink",
            name="payment_method",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
