# Generated by Django 5.0.7 on 2024-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_stripe", "0003_stripepaymentlink_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_link",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
