# Generated by Django 5.0.7 on 2024-08-21 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_stripe", "0004_remove_product_price_link_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripepaymentlink",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment_stripe.product",
            ),
            preserve_default=False,
        ),
    ]
