# Generated by Django 5.0.7 on 2024-08-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_stripe", "0005_stripepaymentlink_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripepaymentlink",
            name="created",
            field=models.DateTimeField(null=True),
        ),
    ]
