# Generated by Django 5.0.6 on 2024-07-11 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IP_resource", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipresource",
            name="description",
        ),
        migrations.AddField(
            model_name="ipresource",
            name="expire_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipresource",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipresource",
            name="password",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ipresource",
            name="port",
            field=models.IntegerField(default=7777),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ipresource",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
