# Generated by Django 5.0.6 on 2024-07-11 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("IP_resource", "0003_ipresource_db_server"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ipresource",
            old_name="db_server",
            new_name="host_server",
        ),
    ]
