# Generated by Django 5.0.6 on 2024-07-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IP_resource", "0005_ipresource_protocol_config"),
        ("cluster", "0007_alter_dbserver_server_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipresource",
            name="protocol_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cluster.protocalconfig",
            ),
        ),
    ]
