# Generated by Django 5.0.6 on 2024-07-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IP_resource", "0007_alter_ipresource_protocol_config"),
        (
            "cluster",
            "0008_alter_dbserver_options_alter_protocalconfig_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ipresource",
            options={
                "verbose_name": "IP Resource",
                "verbose_name_plural": "IP Resources",
            },
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="expire_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expire Date"
            ),
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="host_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="cluster.dbserver",
                verbose_name="Host Server",
            ),
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="ip_address",
            field=models.CharField(max_length=15, verbose_name="IP Address"),
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="password",
            field=models.CharField(max_length=100, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="port",
            field=models.IntegerField(verbose_name="Port"),
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="protocol_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ip_resources",
                to="cluster.protocalconfig",
                verbose_name="Protocal Config",
            ),
        ),
        migrations.AlterField(
            model_name="ipresource",
            name="username",
            field=models.CharField(max_length=100, verbose_name="Username"),
        ),
    ]
