# Generated by Django 5.0.6 on 2024-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cluster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocalconfig",
            name="config_url",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
