# Generated by Django 5.0.6 on 2024-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cluster", "0002_protocalconfig_config_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocalconfig",
            name="down",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="protocalconfig",
            name="enable",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name="protocalconfig",
            name="expiry_time",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="protocalconfig",
            name="total",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="protocalconfig",
            name="up",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
