# Generated by Django 5.0.6 on 2024-07-07 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cluster", "0003_protocalconfig_down_protocalconfig_enable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protocalconfig",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocol_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
