# Generated by Django 5.0.6 on 2024-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cluster", "0005_remove_protocalconfig_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocalconfig",
            name="expiry_time",
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="total",
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
