# Generated by Django 5.0.6 on 2024-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cluster", "0006_alter_protocalconfig_expiry_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbserver",
            name="server_name",
            field=models.CharField(max_length=100),
        ),
    ]
