# Generated by Django 5.0.6 on 2024-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cluster", "0007_alter_dbserver_server_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dbserver",
            options={"verbose_name": "Db Server", "verbose_name_plural": "Db Servers"},
        ),
        migrations.AlterModelOptions(
            name="protocalconfig",
            options={
                "verbose_name": "Protocal Config",
                "verbose_name_plural": "Protocal Configs",
            },
        ),
        migrations.AddField(
            model_name="dbserver",
            name="pem_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Server IP"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dbserver",
            name="server_ip",
            field=models.CharField(max_length=100, verbose_name="Server IP"),
        ),
        migrations.AlterField(
            model_name="dbserver",
            name="server_name",
            field=models.CharField(max_length=100, verbose_name="Server Name"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="alter_id",
            field=models.IntegerField(verbose_name="Alter ID"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="config_url",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Config URL"
            ),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="down",
            field=models.IntegerField(blank=True, default=0, verbose_name="Down"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="enable",
            field=models.IntegerField(blank=True, default=1, verbose_name="Enable"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="expiry_time",
            field=models.IntegerField(
                blank=True, default=-1, verbose_name="Expiry Time"
            ),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="network",
            field=models.CharField(max_length=100, verbose_name="Network"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="network_type",
            field=models.CharField(max_length=100, verbose_name="Network Type"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="port",
            field=models.IntegerField(verbose_name="Port"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="protocal",
            field=models.CharField(max_length=100, verbose_name="Protocol"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="remark",
            field=models.CharField(max_length=100, verbose_name="Remark"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="server_ip",
            field=models.CharField(max_length=100, verbose_name="Server IP"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="total",
            field=models.IntegerField(blank=True, default=-1, verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="up",
            field=models.IntegerField(blank=True, default=0, verbose_name="Up"),
        ),
        migrations.AlterField(
            model_name="protocalconfig",
            name="uuid",
            field=models.CharField(max_length=100, verbose_name="UUID"),
        ),
    ]
