# Generated by Django 5.0.7 on 2024-08-15 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_paypal", "0002_paypalorder_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paypalorder",
            name="user",
        ),
    ]
