# Generated by Django 5.0.7 on 2024-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_paypal", "0004_paypalorder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalorder",
            name="capture_create_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paypalorder",
            name="capture_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paypalorder",
            name="gross_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paypalorder",
            name="net_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="paypalorder",
            name="payer_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalorder",
            name="payer_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalorder",
            name="paypal_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
