# Generated by Django 5.0.7 on 2024-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_paypal", "0005_paypalorder_capture_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
